version: 1.0
workflows:
   - name: "NewCytominer"
     subclass: WDL
     primaryDescriptorPath: /cytomining.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
         tags:
             - /.*/
